/**
 * NOTE FOR USER REVIEW:
 * Please verify/confirm the following values before launch:
 * 1. Uptime / Outage SLA: Outages don't warrant credits but failed runs are refunded (Line 59)
 * 2. Suspension timeline: 3 failed payment attempts over 7 days (Line 54)
 * 3. Support Email: desk@articleship.com (Line 68)
 */

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | ArticleShip Editorial Desk",
  description: "Read the terms, acceptable use policies, and legal disclaimers governing the use of our automated press."
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[#F4F6F9] text-[#0B132B] px-6 py-16 md:px-12 font-serif selection:bg-[#FEF08A] selection:text-[#0B132B]">
      <article className="mx-auto max-w-[800px] space-y-12">
        
        {/* Legal Disclaimer Banner */}
        <div className="bg-amber-50 border-2 border-amber-500 p-5 rounded-none font-mono text-[10px] uppercase tracking-wider text-amber-900 shadow-[3px_3px_0px_rgba(245,158,11,0.1)]">
          <span className="font-extrabold block mb-1">⚠️ Legal Review Notice:</span>
          This document is a draft version compiled for customer preview. It is not legal advice and must be formally reviewed and edited by qualified legal counsel prior to commercial deployment.
        </div>

        <header className="border-b border-[#0B132B]/10 pb-8 space-y-3">
          <p className="text-xs font-mono font-bold uppercase tracking-widest text-[#1D4ED8]">Legal Registry</p>
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight">Terms of Service</h1>
          <p className="text-xs font-mono uppercase text-[#4B5563]">Last Revised: June 2026</p>
        </header>

        <section className="prose prose-stone prose-md space-y-6 text-[#0B132B]">
          <p className="leading-relaxed">
            Welcome to ArticleShip (the &quot;Service&quot;). By accessing our digital manuscript composition tools, you agree to comply with the terms and acceptable use guidelines outlined below.
          </p>

          <h2 className="text-xl font-extrabold pt-4 font-serif">1. Acceptable Content Generation Use</h2>
          <p className="leading-relaxed">
            Our automated press is designed to assist writers, bloggers, and agencies in generating high-quality draft manuscripts. You agree not to use the Service to generate:
          </p>
          <ul className="list-disc pl-5 space-y-2 font-mono text-[11px] uppercase tracking-wider text-[#4B5563]">
            <li>Content for illegal, defamatory, or deceptive purposes.</li>
            <li>Low-quality web spam or automated link farm schemes.</li>
            <li>Plagiarized drafts that violate existing copyright or trademarks.</li>
            <li>Harassment, threats, or hate speech payloads.</li>
          </ul>

          <h2 className="text-xl font-extrabold pt-4 font-serif">2. AI-Authored Content Disclaimer</h2>
          <p className="leading-relaxed">
            All generated manuscripts, outlines, and image recommendations are generated by AI systems (including Google Gemini). <strong>You are the publisher and editor of the content.</strong> You must review, verify, and check all facts, figures, and plagiarism checkers before publishing. ArticleShip is not liable for technical inaccuracies, ranking drops, or copyright disputes arising from your published articles.
          </p>

          <h2 className="text-xl font-extrabold pt-4 font-serif">3. Billing and Payment Failures</h2>
          <p className="leading-relaxed">
            Payment processing is managed via secure third-party portals. If a subscription renewal payment fails, we will attempt to retry the charge three (3) times over a seven (7) day period. If payment remains outstanding after 7 days, your premium access desk and pending scheduled stagger runs will be suspended.
          </p>

          <h2 className="text-xl font-extrabold pt-4 font-serif">4. Outage and Service Interruption Policy</h2>
          <p className="leading-relaxed">
            Because our pipeline depends on third-party APIs (Google Gemini, Unsplash, Google Search), we cannot guarantee 100% uninterrupted generation uptime. Service downtime, queue stalls, or API limits do not constitute grounds for cash refunds. However, any failed generation run will have its credits fully restored to your account registry.
          </p>

          <h2 className="text-xl font-extrabold pt-4 font-serif">5. Revisions and Inquiries</h2>
          <p className="leading-relaxed">
            We reserve the right to modify these terms. If you have questions, please reach out to us at: <a href="mailto:desk@articleship.com" className="text-[#1E3A8A] font-bold hover:underline">desk@articleship.com</a>.
          </p>
        </section>

        <div className="pt-8 border-t border-[#0B132B]/10">
          <Link 
            href="/" 
            className="inline-flex items-center justify-center rounded-none border-2 border-[#0B132B] bg-white px-6 py-3 text-xs font-mono font-bold uppercase tracking-wider shadow-[2px_2px_0px_rgba(11,19,43,1)] hover:bg-[#F4F6F9]"
          >
            &larr; Return to Home Desk
          </Link>
        </div>
      </article>
    </main>
  );
}
