import os
import json
from dotenv import load_dotenv
from google import genai
from google.genai import types

# Load environment variables
load_dotenv()

# We expect GEMINI_API_KEY from .env
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

async def build_article_structure(topic: str, seo_data: dict) -> dict:
    """
    Takes the topic and SEO keywords generated by the keyword engine
    and creates a structured article outline with proper H1, H2, H3 hierarchy.
    """
    prompt = f"""
You are a senior Content Strategist and SEO architect. Your task is to generate a deeply structured, SEO-optimized article outline for 'ArticleShip'.

TOPIC: "{topic}"

SEO DATA:
{json.dumps(seo_data, indent=2)}

STRUCTURE RULES:
1. H1 (exactly one): Must be compelling and click-worthy. Incorporate the primary keyword naturally — do not lead with it robotically. Aim for curiosity or a strong claim.
2. H2s (4–7 required): Each H2 is a major standalone section. Distribute secondary keywords across H2 headings — one secondary keyword per H2 where it fits naturally. Do not force it.
3. H3s (2–4 per H2): Break each H2 into focused sub-topics. Use long-tail keywords in H3s where relevant — they signal content depth to Google.
4. H4s (optional, use sparingly): Only add H4s when a sub-topic has 2+ genuinely distinct sub-points. Leave h4_tags as [] if not needed.
5. Content variety (required): The overall structure MUST include:
   - At least one comparison or "X vs Y" section
   - At least one how-to, step-by-step, or practical guide section
   - At least one FAQ, myth-busting, or "common mistakes" section
6. Keyword placement map:
   - Primary keyword → H1 and at least one H2
   - Secondary keywords → H2 headings
   - Long-tail keywords → H3 headings
   - LSI keywords → inform H3/H4 topics but need not appear verbatim in headings
7. No redundancy: Every heading must cover a distinct angle. Do not create two H2s that overlap in scope.

OUTPUT: A single valid JSON object only. No markdown fences. No explanation. No trailing commas.

Schema:
{{
  "h1": "string",
  "sections": [
    {{
      "h2": "string",
      "subsections": [
        {{
          "h3": "string",
          "h4_tags": []
        }}
      ]
    }}
  ]
}}
"""

    try:
        response = client.models.generate_content(
            model='gemini-3-flash-preview',
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
            ),
        )

        # Parse JSON string from LLM
        content_str = response.text
        return json.loads(content_str)
        
    except Exception as e:
        return {"error": str(e), "message": "Failed to generate structure response."}
