import os
import json
import asyncio
from dotenv import load_dotenv
from google import genai
from google.genai import types
from duckduckgo_search import DDGS

# Load environment variables
load_dotenv()

# We expect GEMINI_API_KEY from .env
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


def _retrieve_structure_context_sync(topic: str) -> str:
  snippets: list[str] = []

  try:
    ddgs = DDGS()
    queries = [
      f"{topic} implementation guide",
      f"{topic} common mistakes",
      f"{topic} best practices 2025"
    ]

    for query in queries:
      results = list(ddgs.text(query, max_results=2))
      for result in results:
        body = str(result.get("body", "") or "").strip()
        if body:
          snippets.append(body)

  except Exception as error:
    print(f"Structure retrieval failed: {error}")

  if not snippets:
    return "No live search context available."

  unique_snippets = list(dict.fromkeys(snippets))
  return "\n".join(unique_snippets[:6])


def _generate_structure_sync(prompt: str):
  return client.models.generate_content(
    model='gemini-3-flash-preview',
    contents=prompt,
    config=types.GenerateContentConfig(
      response_mime_type="application/json",
    ),
  )

async def build_article_structure(topic: str, seo_data: dict) -> dict:
    """
    Takes the topic and SEO keywords generated by the keyword engine
    and creates a structured article outline with proper H1, H2, H3 hierarchy.
    """
    search_context = await asyncio.to_thread(_retrieve_structure_context_sync, topic)

    prompt = f"""You are a senior Content Strategist and SEO architect. Your task is to generate a deeply structured, SEO-optimized article outline for 'ArticleShip'.

TOPIC: "{topic}"

  SEARCH CONTEXT (live retrieval snippets):
  {search_context}

SEO DATA:
{json.dumps(seo_data, indent=2)}

CONTENT ANGLE (use this as the differentiation hook — the article must lead with this):
{seo_data.get('content_angle', '')}

STRUCTURE RULES:

1. H1 (exactly one): Must be compelling and click-worthy. Follow this formula: [Primary keyword] + [year or recency signal] + [curiosity gap or strong claim]. Keep under 65 characters for Google display. Incorporate the primary keyword naturally — do not lead with it robotically. The title MUST reflect the full article topic, not a single section within it. If the article is a 30-day review, the title must say "30-day review" — not the name of a specific technique covered in one section.
   Wrong: "Husky Pre-Commit Hook for AI Code Complexity"  ← this is a section title, not the article title
   Right: "GitHub Copilot Real World Review 2025: What Actually Broke"

2. H2s (4–7 required): Each H2 is a major standalone section. Distribute secondary keywords across H2 headings — one secondary keyword per H2 where it fits naturally. Do not force it.
   REQUIRED: At least one H2 must be explicitly failure/risk-focused (e.g. "Where Copilot Actually Failed Us"). Generic positive-only structures will not rank against experienced practitioners who document real problems.
   REQUIRED: No two H2s may overlap in scope. Before finalising, check each H2 pair — if both could contain the same paragraph, one of them is redundant.

3. H3s (2–4 per H2): Break each H2 into focused sub-topics. Use long-tail keywords in H3s where relevant — they signal content depth to Google.
   REQUIRED: At least one H3 per article must be a named-mistake or specific-scenario heading (e.g. "The Binary Search Bug That Passed Code Review" or "How Copilot Broke Our Auth Middleware"). These dramatically increase dwell time and social sharing.

4. H4s (optional, use sparingly): Only add H4s when a sub-topic has 2+ genuinely distinct sub-points. Leave h4_tags as [] if not needed.

5. Content variety (required): The overall structure MUST include:
   - At least one comparison or "X vs Y" section
   - At least one how-to, step-by-step, or practical guide section
   - At least one FAQ, myth-busting, or "common mistakes" section
   CRITICAL — FAQ DEDUPLICATION: The FAQ section heading must cover questions that are NOT already answered as standalone H2 or H3 headings elsewhere in the outline. Scan the full structure before writing the FAQ heading. If a question already has its own section, it is banned from the FAQ.

6. Keyword placement map:
   - Primary keyword → H1 and at least one H2
   - Secondary keywords → H2 headings
   - Long-tail keywords → H3 headings
   - LSI keywords → inform H3/H4 topics but need not appear verbatim in headings

7. SKIMMABILITY ANCHORS (new — addresses bounce rate problem): For each H2, add a skimmability_hook field: a single sentence (max 15 words) that summarises the section's core takeaway. This will be used by the rendering system to generate pull-quotes and section previews that keep readers on-page.
   Example: "Copilot is 70% faster on CRUD but actively harmful during deep algorithm design."

8. No redundancy: Every heading must cover a distinct angle. Do not create two H2s that overlap in scope.

9. RETRIEVAL GROUNDING (required): Use the SEARCH CONTEXT to align headings with real search phrasing and practical user questions. Do not copy sentences verbatim, and do not invent named tools/stats not supported by either SEO DATA or search context.

OUTPUT: A single valid JSON object only. No markdown fences. No explanation. No trailing commas.

Schema:
{{
  "h1": "string",
  "sections": [
    {{
      "h2": "string",
      "skimmability_hook": "string",
      "subsections": [
        {{
          "h3": "string",
          "h4_tags": []
        }}
      ]
    }}
  ]
}}"""

    try:
        response = await asyncio.to_thread(_generate_structure_sync, prompt)

        # Parse JSON string from LLM
        content_str = response.text
        return json.loads(content_str)

    except Exception as e:
        return {"error": str(e), "message": "Failed to generate structure response."}
